const PerformersData = [
    {
        key: "performerData1",
        profileImg: "/images/profile/user-3.jpg",
        username: "Carol Davis",
        designation: "HR Specialist",
        project: "People Ops",
        priority: "Deep focus",
        color: "primary",
        bgcolor: "bg-primary text-white",
        budget: "3.9k",
    },
    {
        key: "performerData2",
        profileImg: "/images/profile/user-5.jpg",
        username: "Eve Green",
        designation: "Software Engineer",
        project: "Product",
        priority: "In the Clubhouse",
        color: "warning",
        bgcolor: "bg-success text-white",
        budget: "24.5k",
    },
    {
        key: "performerData3",
        profileImg: "/images/profile/user-6.jpg",
        username: "Frank White",
        designation: "Sales Rep",
        project: "Revenue",
        priority: "Out today",
        color: "warning",
        bgcolor: "bg-error text-white",
        budget: "12.8k",
    },
    {
        key: "performerData4",
        profileImg: "/images/profile/user-7.jpg",
        username: "Grace Black",
        designation: "Financial Analyst",
        project: "Finance",
        priority: "On break",
        color: "success",
        bgcolor: "bg-warning text-white",
        budget: "4.8k",
    },
    {
        key: "performerData5",
        profileImg: "/images/profile/user-8.jpg",
        username: "Henry King",
        designation: "CEO",
        project: "Executive",
        priority: "In the Clubhouse",
        color: "error",
        bgcolor: "bg-success text-white",
        budget: "9.3k",
    },
];

const RecognitionData = [
    {
        key: "recognition1",
        fromImg: "/images/profile/user-1.jpg",
        fromName: "Alice Johnson",
        toImg: "/images/profile/user-5.jpg",
        toName: "Eve Green",
        badge: "Star of the day",
        badgeBg: "bg-yellow-100 text-yellow-700",
        reason: "5 days of deep work",
        when: "2h ago",
    },
    {
        key: "recognition2",
        fromImg: "/images/profile/user-4.jpg",
        fromName: "David Brown",
        toImg: "/images/profile/user-3.jpg",
        toName: "Carol Davis",
        badge: "Focus hero",
        badgeBg: "bg-blue-100 text-blue-700",
        reason: "Hosted a team lunch",
        when: "Yesterday",
    },
    {
        key: "recognition3",
        fromImg: "/images/profile/user-2.jpg",
        fromName: "Bob Williams",
        toImg: "/images/profile/user-8.jpg",
        toName: "Henry King",
        badge: "Team spark",
        badgeBg: "bg-green-100 text-green-700",
        reason: "Helped unblock a project",
        when: "Yesterday",
    },
    {
        key: "recognition4",
        fromImg: "/images/profile/user-6.jpg",
        fromName: "Frank White",
        toImg: "/images/profile/user-1.jpg",
        toName: "Alice Johnson",
        badge: "Star of the day",
        badgeBg: "bg-yellow-100 text-yellow-700",
        reason: "Led the sprint retro",
        when: "This week",
    },
    {
        key: "recognition5",
        fromImg: "/images/profile/user-7.jpg",
        fromName: "Grace Black",
        toImg: "/images/profile/user-2.jpg",
        toName: "Bob Williams",
        badge: "Focus hero",
        badgeBg: "bg-blue-100 text-blue-700",
        reason: "Shipped a feature solo",
        when: "This week",
    },
];

export { PerformersData, RecognitionData }