import type { TeamMember, CurrentUser } from '@/app/(DashboardLayout)/types/team';

export const currentUser: CurrentUser = {
  id: 'usr-001',
  role: 'HR',
  fullName: 'Sarah Mitchell',
  managedTeams: undefined,
};

export const teamMembers: TeamMember[] = [
  {
    id: 'tm-001',
    fullName: 'James Carter',
    preferredName: 'Jim',
    roleTitle: 'Senior Frontend Engineer',
    primaryTeam: 'Engineering',
    managerName: 'Laura Bennett',
    location: 'London, UK',
    timeZone: 'Europe/London',
    workPattern: 'HYBRID',
    companyName: 'Milestone Ltd',
    hasOpenTickets: true,
    openTicketsCount: 2,
    onboardingStatus: 'COMPLETED',
  },
  {
    id: 'tm-002',
    fullName: 'Priya Patel',
    roleTitle: 'Product Designer',
    primaryTeam: 'Design',
    managerName: 'Laura Bennett',
    location: 'Mumbai, India',
    timeZone: 'Asia/Kolkata',
    workPattern: 'REMOTE',
    companyName: 'Milestone Ltd',
    hasOpenTickets: false,
    openTicketsCount: 0,
    onboardingStatus: 'COMPLETED',
  },
  {
    id: 'tm-003',
    fullName: 'Carlos Reyes',
    preferredName: 'Charlie',
    roleTitle: 'Backend Engineer',
    primaryTeam: 'Engineering',
    managerName: 'Laura Bennett',
    location: 'Madrid, Spain',
    timeZone: 'Europe/Madrid',
    workPattern: 'REMOTE',
    companyName: 'Milestone Ltd',
    hasOpenTickets: true,
    openTicketsCount: 1,
    onboardingStatus: 'COMPLETED',
  },
  {
    id: 'tm-004',
    fullName: 'Emily Nguyen',
    roleTitle: 'HR Coordinator',
    primaryTeam: 'People Ops',
    managerName: 'Sarah Mitchell',
    location: 'Sydney, Australia',
    timeZone: 'Australia/Sydney',
    workPattern: 'OFFICE',
    companyName: 'Milestone Ltd',
    hasOpenTickets: false,
    openTicketsCount: 0,
    onboardingStatus: 'IN_PROGRESS',
  },
  {
    id: 'tm-005',
    fullName: 'Michael Thompson',
    preferredName: 'Mike',
    roleTitle: 'Sales Manager',
    primaryTeam: 'Sales',
    managerName: 'David Kim',
    location: 'New York, US',
    timeZone: 'America/New_York',
    workPattern: 'OFFICE',
    companyName: 'Milestone Ltd',
    hasOpenTickets: true,
    openTicketsCount: 3,
    onboardingStatus: 'COMPLETED',
  },
  {
    id: 'tm-006',
    fullName: 'Anya Sokolova',
    roleTitle: 'QA Engineer',
    primaryTeam: 'Engineering',
    managerName: 'Laura Bennett',
    location: 'Berlin, Germany',
    timeZone: 'Europe/Berlin',
    workPattern: 'HYBRID',
    companyName: 'Milestone Ltd',
    hasOpenTickets: false,
    openTicketsCount: 0,
    onboardingStatus: 'COMPLETED',
  },
  {
    id: 'tm-007',
    fullName: 'David Kim',
    roleTitle: 'VP of Sales',
    primaryTeam: 'Sales',
    managerName: 'Sarah Mitchell',
    location: 'San Francisco, US',
    timeZone: 'America/Los_Angeles',
    workPattern: 'OFFICE',
    companyName: 'Milestone Ltd',
    hasOpenTickets: true,
    openTicketsCount: 1,
    onboardingStatus: 'COMPLETED',
  },
  {
    id: 'tm-008',
    fullName: 'Fatima Al-Rashid',
    roleTitle: 'Marketing Specialist',
    primaryTeam: 'Marketing',
    managerName: 'David Kim',
    location: 'Dubai, UAE',
    timeZone: 'Asia/Dubai',
    workPattern: 'REMOTE',
    companyName: 'Milestone Ltd',
    hasOpenTickets: false,
    openTicketsCount: 0,
    onboardingStatus: 'PENDING',
  },
  {
    id: 'tm-009',
    fullName: 'Laura Bennett',
    roleTitle: 'Engineering Manager',
    primaryTeam: 'Engineering',
    managerName: 'Sarah Mitchell',
    location: 'London, UK',
    timeZone: 'Europe/London',
    workPattern: 'HYBRID',
    companyName: 'Milestone Ltd',
    hasOpenTickets: true,
    openTicketsCount: 2,
    onboardingStatus: 'COMPLETED',
  },
  {
    id: 'tm-010',
    fullName: 'Tomoko Sato',
    roleTitle: 'Data Analyst',
    primaryTeam: 'Engineering',
    managerName: 'Laura Bennett',
    location: 'Tokyo, Japan',
    timeZone: 'Asia/Tokyo',
    workPattern: 'REMOTE',
    companyName: 'Milestone Ltd',
    hasOpenTickets: false,
    openTicketsCount: 0,
    onboardingStatus: 'COMPLETED',
  },
];
